using Microsoft.Data.Sqlite;
using System.Globalization;
using System.Net;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.UseStaticFiles();
var db = Path.Combine(app.Environment.ContentRootPath, "sheehan_lights.db");
Init();
string Cs() => $"Data Source={db}";

app.MapGet("/", async () => Html("Dashboard", await Dashboard(), "home"));
app.MapGet("/products", async () => Html("Products", await Products(), "products"));
app.MapPost("/products", async (HttpRequest r) => { var f=await r.ReadFormAsync(); await Exec("INSERT INTO products(name,sku,category,buying_price,selling_price,stock_qty,low_stock_level,created_at) VALUES($n,$s,$c,$b,$p,$q,$l,$d)", c=>{P(c,"$n",f["name"].ToString().Trim());P(c,"$s",f["sku"].ToString().Trim());P(c,"$c",string.IsNullOrWhiteSpace(f["category"]) ? "General" : f["category"].ToString().Trim());P(c,"$b",Num(f["buying_price"]));P(c,"$p",Num(f["selling_price"]));P(c,"$q",Int(f["stock_qty"]));P(c,"$l",Math.Max(1,Int(f["low_stock_level"])));P(c,"$d",DateTime.Now.ToString("O"));});return Results.Redirect("/products"); });
app.MapPost("/stock", async (HttpRequest r) => { var f=await r.ReadFormAsync(); var delta=Int(f["qty"])*(f["mode"]=="out"?-1:1); await Exec("UPDATE products SET stock_qty=MAX(0,stock_qty+$d) WHERE id=$id", c=>{P(c,"$d",delta);P(c,"$id",Int(f["id"]));});return Results.Redirect("/products");});
app.MapGet("/sales", async () => Html("New Sale", await SaleForm(), "sales"));
app.MapPost("/sales", async (HttpRequest r) => { var f=await r.ReadFormAsync(); var pid=Int(f["product_id"]);var qty=Int(f["qty"]);var payment=string.IsNullOrWhiteSpace(f["payment"]) ? "Cash" : f["payment"].ToString();var discount=Num(f["discount"]);if(pid<=0||qty<=0)return Results.BadRequest("Invalid sale.");await using var c=new SqliteConnection(Cs());await c.OpenAsync();await using var tx=await c.BeginTransactionAsync();try{var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT name,selling_price,stock_qty FROM products WHERE id=$id";q.Parameters.AddWithValue("$id",pid);await using var rd=await q.ExecuteReaderAsync();if(!await rd.ReadAsync())throw new Exception("Product not found.");var name=rd.GetString(0);var price=rd.GetDouble(1);var stock=rd.GetInt32(2);await rd.DisposeAsync();if(stock<qty)throw new Exception("Not enough stock for "+name+".");var subtotal=price*qty;discount=Math.Min(Math.Max(0,discount),subtotal);var total=subtotal-discount;var inv="SL-"+DateTime.Now.ToString("yyyyMMdd-HHmmss");var s=c.CreateCommand();s.Transaction=tx;s.CommandText="INSERT INTO sales(invoice_no,product_id,quantity,unit_price,discount,total,payment_method,created_at) VALUES($i,$p,$q,$u,$d,$t,$m,$dte)";P(s,"$i",inv);P(s,"$p",pid);P(s,"$q",qty);P(s,"$u",price);P(s,"$d",discount);P(s,"$t",total);P(s,"$m",payment);P(s,"$dte",DateTime.Now.ToString("O"));await s.ExecuteNonQueryAsync();var st=c.CreateCommand();st.Transaction=tx;st.CommandText="UPDATE products SET stock_qty=stock_qty-$q WHERE id=$p";P(st,"$q",qty);P(st,"$p",pid);await st.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Content(Html("Sale Complete",$"<section class='card'><span class='eyebrow'>SUCCESS</span><h1>Sale completed</h1><p>Invoice <strong>{E(inv)}</strong> · {E(name)} × {qty}</p><h2>{Money(total)}</h2><p>Payment: {E(payment)}</p><a class='primary' href='/sales'>New sale</a> <a class='secondary' href='/'>Dashboard</a></section>","sales"),"text/html");}catch(Exception ex){await tx.RollbackAsync();return Results.BadRequest(ex.Message);} });
app.MapGet("/reports", async () => Html("Reports", await Reports(), "reports"));
app.MapGet("/settings", async () => Html("Settings", await Settings(), "settings"));
app.MapPost("/settings", async (HttpRequest r) => {var f=await r.ReadFormAsync();await Exec("UPDATE settings SET shop_name=$n,phone=$p,address=$a WHERE id=1",c=>{P(c,"$n",f["shop_name"].ToString().Trim());P(c,"$p",f["phone"].ToString().Trim());P(c,"$a",f["address"].ToString().Trim());});return Results.Redirect("/settings");});
app.Run();

void Init(){using var c=new SqliteConnection(Cs());c.Open();using var x=c.CreateCommand();x.CommandText=@"CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY,shop_name TEXT NOT NULL,phone TEXT,address TEXT);CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,sku TEXT,category TEXT NOT NULL,buying_price REAL NOT NULL,selling_price REAL NOT NULL,stock_qty INTEGER NOT NULL,low_stock_level INTEGER NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_no TEXT NOT NULL UNIQUE,product_id INTEGER NOT NULL,quantity INTEGER NOT NULL,unit_price REAL NOT NULL,discount REAL NOT NULL,total REAL NOT NULL,payment_method TEXT NOT NULL,created_at TEXT NOT NULL);INSERT OR IGNORE INTO settings(id,shop_name,phone,address) VALUES(1,'Sheehan Lights','','');";x.ExecuteNonQuery();using var k=c.CreateCommand();k.CommandText="SELECT COUNT(*) FROM products";if(Convert.ToInt32(k.ExecuteScalar())==0){foreach(var p in new[]{("LED Bulb 12W","LGT-001","LED Bulbs",2500d,4000d,30,5),("LED Bulb 18W","LGT-002","LED Bulbs",4000d,6000d,25,5),("LED Strip 5M","LGT-003","LED Strips",9000d,15000d,15,3),("Ceiling Light 24W","LGT-004","Ceiling Lights",18000d,28000d,10,2),("Flood Light 50W","LGT-005","Outdoor Lights",25000d,38000d,8,2),("2-Way Switch","ELC-001","Electrical Tools",1500d,2500d,50,10),("13A Socket","ELC-002","Electrical Tools",3000d,5000d,40,10),("Electrical Tape","ELC-003","Electrical Tools",800d,1500d,60,15)}){using var i=c.CreateCommand();i.CommandText="INSERT INTO products(name,sku,category,buying_price,selling_price,stock_qty,low_stock_level,created_at) VALUES($n,$s,$c,$b,$p,$q,$l,$d)";P(i,"$n",p.Item1);P(i,"$s",p.Item2);P(i,"$c",p.Item3);P(i,"$b",p.Item4);P(i,"$p",p.Item5);P(i,"$q",p.Item6);P(i,"$l",p.Item7);P(i,"$d",DateTime.Now.ToString("O"));i.ExecuteNonQuery();}}}

async Task<int> Exec(string sql,Action<SqliteCommand> bind){await using var c=new SqliteConnection(Cs());await c.OpenAsync();await using var x=c.CreateCommand();x.CommandText=sql;bind(x);return await x.ExecuteNonQueryAsync();}
async Task<List<Dictionary<string,object?>>> Q(string sql,Action<SqliteCommand>? bind=null){await using var c=new SqliteConnection(Cs);await c.OpenAsync();await using var x=c.CreateCommand();x.CommandText=sql;bind?.Invoke(x);await using var r=await x.ExecuteReaderAsync();var a=new List<Dictionary<string,object?>>();while(await r.ReadAsync()){var d=new Dictionary<string,object?>();for(int i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);a.Add(d);}return a;}
void P(SqliteCommand c,string n,object? v)=>c.Parameters.AddWithValue(n,v??DBNull.Value);
int Int(string s)=>int.TryParse(s,NumberStyles.Integer,CultureInfo.InvariantCulture,out var n)?n:0;double Num(string s)=>double.TryParse(s,NumberStyles.Number,CultureInfo.InvariantCulture,out var n)?n:0d;string E(object? v)=>WebUtility.HtmlEncode(v?.ToString()??"");string Money(object? v)=>"TSh "+Convert.ToDecimal(v??0).ToString("N0",CultureInfo.InvariantCulture);
string Html(string title,string body,string active)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{E(title)} · Sheehan Lights</title><link rel='stylesheet' href='/style.css'></head><body><header class='topbar'><div class='brand'>SHEEHAN <span>LIGHTS</span><small>BUSINESS MANAGER</small></div><nav><a class='{(active=="home"?"on":"")}' href='/'>Dashboard</a><a class='{(active=="sales"?"on":"")}' href='/sales'>New Sale</a><a class='{(active=="products"?"on":"")}' href='/products'>Products</a><a class='{(active=="reports"?"on":"")}' href='/reports'>Reports</a><a class='{(active=="settings"?"on":"")}' href='/settings'>Settings</a></nav></header><main>{body}</main><footer>Sheehan Lights · HybridBusinessPOS · SQLite</footer></body></html>";
async Task<string> Dashboard(){var s=(await Q("SELECT shop_name FROM settings WHERE id=1")).First();var t=DateTime.Now.ToString("yyyy-MM-dd");var a=(await Q($"SELECT COALESCE(SUM(total),0) sales,COUNT(*) count FROM sales WHERE substr(created_at,1,10)='{t}'"))[0];var p=(await Q("SELECT COUNT(*) products,COALESCE(SUM(selling_price*stock_qty),0) stock_value,COALESCE(SUM(CASE WHEN stock_qty<=low_stock_level THEN 1 ELSE 0 END),0) low FROM products"))[0];var recent=await Q("SELECT s.invoice_no,p.name,s.quantity,s.total,s.payment_method FROM sales s JOIN products p ON p.id=s.product_id ORDER BY s.id DESC LIMIT 8");return $"<div class='head'><div><span class='eyebrow'>SHOP MANAGEMENT</span><h1>{E(s["shop_name"])}</h1><p>Simple control for lights and electrical tools.</p></div><a class='primary' href='/sales'>+ New Sale</a></div><div class='cards'><div class='card'><span>Today's Sales</span><strong>{Money(a["sales"])}</strong><small>{a["count"]} transactions</small></div><div class='card'><span>Products</span><strong>{p["products"]}</strong><small>catalogue items</small></div><div class='card'><span>Stock Value</span><strong>{Money(p["stock_value"])}</strong><small>at selling price</small></div><div class='card'><span>Low Stock</span><strong>{p["low"]}</strong><small>items needing restock</small></div></div><section class='card'><div class='title'><h2>Recent Sales</h2><a href='/reports'>View reports →</a></div><div class='tablewrap'><table><tr><th>Invoice</th><th>Product</th><th>Qty</th><th>Payment</th><th>Total</th></tr>{string.Join("",recent.Select(r=>$"<tr><td>{E(r["invoice_no"])}</td><td>{E(r["name"])}</td><td>{r["quantity"]}</td><td>{E(r["payment_method"])}</td><td><b>{Money(r["total"])}</b></td></tr>"))}</table></div></section>";}
async Task<string> Products(){var rows=await Q("SELECT * FROM products ORDER BY category,name");return $"<div class='head'><div><span class='eyebrow'>INVENTORY</span><h1>Products</h1><p>Add products and adjust stock.</p></div></div><div class='two'><section class='card'><div class='title'><h2>Add Product</h2></div><form method='post' action='/products' class='form'><input name='name' required placeholder='Product name'><input name='sku' placeholder='SKU'><input name='category' value='LED Bulbs' placeholder='Category'><input name='buying_price' type='number' min='0' step='0.01' placeholder='Buying price'><input name='selling_price' type='number' min='0' step='0.01' placeholder='Selling price' required><input name='stock_qty' type='number' min='0' placeholder='Opening stock' required><input name='low_stock_level' type='number' min='1' value='5'><button class='primary'>Save product</button></form></section><section class='card'><div class='title'><h2>Stock Adjustment</h2></div><form method='post' action='/stock' class='form'><select name='id'>{string.Join("",rows.Select(r=>$"<option value='{r["id"]}'>{E(r["name"])} — stock {r["stock_qty"]}</option>"))}</select><input name='qty' type='number' min='1' value='1'><select name='mode'><option value='in'>Stock In</option><option value='out'>Stock Out</option></select><button class='secondary'>Apply</button></form></section></div><section class='card'><div class='title'><h2>Product List</h2><span>{rows.Count} items</span></div><div class='tablewrap'><table><tr><th>Product</th><th>Category</th><th>SKU</th><th>Selling</th><th>Stock</th></tr>{string.Join("",rows.Select(r=>$"<tr><td><b>{E(r["name"])}</b></td><td>{E(r["category"])}</td><td>{E(r["sku"])}</td><td>{Money(r["selling_price"])}</td><td><span class='stock {(Convert.ToInt32(r["stock_qty"])<=Convert.ToInt32(r["low_stock_level"])?"low":"")}'>{r["stock_qty"]}</span></td></tr>"))}</table></div></section>";}
async Task<string> SaleForm(){var rows=await Q("SELECT * FROM products WHERE stock_qty>0 ORDER BY name");return $"<div class='head'><div><span class='eyebrow'>POINT OF SALE</span><h1>New Sale</h1><p>Complete a quick sale and reduce stock automatically.</p></div></div><section class='card'><form method='post' action='/sales' class='form'><select name='product_id' required>{string.Join("",rows.Select(r=>$"<option value='{r["id"]}'>{E(r["name"])} · {Money(r["selling_price"])} · stock {r["stock_qty"]}</option>"))}</select><input name='qty' type='number' min='1' value='1' required><input name='discount' type='number' min='0' step='0.01' value='0' placeholder='Discount'><select name='payment'><option>Cash</option><option>M-Pesa</option><option>Card</option><option>Bank</option></select><button class='primary'>Complete Sale</button></form></section>";}
async Task<string> Reports(){var rows=await Q("SELECT s.invoice_no,p.name,s.quantity,s.unit_price,s.discount,s.total,s.payment_method,s.created_at FROM sales s JOIN products p ON p.id=s.product_id ORDER BY s.id DESC LIMIT 200");return $"<div class='head'><div><span class='eyebrow'>REPORTS</span><h1>Sales History</h1><p>Completed transactions for the shop.</p></div><a class='primary' href='/sales'>+ New Sale</a></div><section class='card'><div class='tablewrap'><table><tr><th>Invoice</th><th>Date</th><th>Product</th><th>Qty</th><th>Payment</th><th>Discount</th><th>Total</th></tr>{string.Join("",rows.Select(r=>$"<tr><td>{E(r["invoice_no"])}</td><td>{DateTime.Parse(r["created_at"]!.ToString()!).ToString("dd MMM yyyy HH:mm")}</td><td>{E(r["name"])}</td><td>{r["quantity"]}</td><td>{E(r["payment_method"])}</td><td>{Money(r["discount"])}</td><td><b>{Money(r["total"])}</b></td></tr>"))}</table></div></section>";}
async Task<string> Settings(){var r=(await Q("SELECT * FROM settings WHERE id=1"))[0];return $"<div class='head'><div><span class='eyebrow'>BUSINESS SETUP</span><h1>Settings</h1><p>Shop details used by the manager.</p></div></div><section class='card'><form method='post' action='/settings' class='form'><input name='shop_name' value='{E(r["shop_name"])}' placeholder='Shop name' required><input name='phone' value='{E(r["phone"])}' placeholder='Phone'><input name='address' value='{E(r["address"])}' placeholder='Address'><button class='primary'>Save settings</button></form></section>";}